services:
  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=kanban
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U user -d kanban
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

  adminer: 
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - database
