version: '3.8'

services:

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=kanban
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  admin:
    image: adminer
    depends_on: 
      - database
    ports:
      - 8080:8080