services:

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    environment:
      - DATABASE_URL=postgres://user:mypassword@database:5432/kanban
    ports:
      - 5173:5173
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=kanban
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U user -d kanban
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

  adminer: 
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - database

  # nginx:
  #   container_name: reverseproxy
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./reverseproxy/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #     - adminer
  #     - database
