name: Pagesspeed

on:
  push:
    branches: -main

jobs:
  pagespeed:
    runs-on: ubuntu-latest
    steps:
      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1.3
        id: psi
        with:
          url: "https://jake.partus.ch"
          threshold: 70
          strategy: mobile
          key: ${{ secrets.APIKEY }}

  surge:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to foo-bar.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "foo-bar.surge.sh"
          project: "."
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
