name: Surge

on:
  push:
    branches: -main

jobs:
  surge:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to foo-bar.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "foo-bar.surge.sh"
          project: "."
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
